meta:
  engine: 4.2.1
  version: 0.1.0
  author: Edward Evans
units:
  # proxy spacing vars
  kx: cx
  ky: cy
  # padding vars
  px: kx + 4
  py: ky + 4
  # case padding vars
  dpx: kx + 8
  dpy: ky + 8
  # render choc spacings
  $default_width: cx
  $default_height: cy
  # mount hole radius
  mountRadius: 1
points:
  zones:
    matrix:
      # fix kicad placement
      anchor:
        shift: [150, -150]
      key:
        padding: u
        spread: 1kx
      columns:
        pinky:
          key:
            splay: 9
            column_net: GP15
        ring:
          key:
            spread: 1kx + 1.8
            splay: -9
            stagger: 5
            column_net: GP14
        middle:
          key:
            stagger: 5
            column_net: GP13
        index:
          key:
            stagger: -5
            column_net: GP12
        inner:
          key:
            spread: 1kx + 1.2
            splay: -5
            stagger: -2.0
            column_net: GP11
      rows:
        bottom:
          row_net: GP27
        home:
          row_net: GP28
        top:
          row_net: GP29
    thumbs:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: matrix_index_bottom
        shift: [-3, -1.2ky]
      columns:
        mod:
          key:
            splay: -4.5
            column_net: GP13
        layer:
          key:
            spread: 1kx + 2.5
            splay: -12
            shift: [0, -2.1]
            column_net: GP12
        space:
          key:
            spread: 1kx + 3
            splay: -12
            shift: [0, -4.2]
            column_net: GP11
      rows:
        cluster:
          row_net: GP26
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [13.8, 13.8]
  pcb_board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_top
          shift: [0.7px, 0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_top
          shift: [0.3px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [0.5px, 0.5py]
        - ref: matrix_index_top
          shift: [-0.3px, 0.5py]
        - ref: matrix_index_top
          shift: [0.4px, 0.5py]
        - ref: matrix_inner_top
          shift: [-0.3px, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px, 0.53py]
        # start MCU / interconnect space
        - ref: matrix_inner_top
          shift: [1.7px, 0.62py]
        - ref: matrix_inner_bottom
          shift: [1.94px, -0.5py]
        - ref: thumbs_space_cluster
          shift: [0.5px, 0.5py]
        # end MCU /interconnect space
        - ref: thumbs_space_cluster
          shift: [0.5px, -0.5py]
        - ref: thumbs_layer_cluster
          shift: [0.3px, -0.5py]
        - ref: thumbs_layer_cluster
          shift: [-0.4px, -0.5py]
        - ref: thumbs_mod_cluster
          shift: [-0.5px, -0.5py]
        - ref: matrix_index_bottom
          shift: [-0.6px, -0.5py]
        - ref: matrix_middle_bottom
          shift: [-0.3px, -0.75py]
        - ref: matrix_ring_bottom
          shift: [-0.3px, -0.55py]
        - ref: matrix_pinky_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px, -0.5py]
      fillet: 2
  switch_plate:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_pinky_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_pinky_top
          shift: [0.7px, 0.5py]
        - ref: matrix_ring_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_top
          shift: [0.3px, 0.5py]
        - ref: matrix_middle_top
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_top
          shift: [0.5px, 0.5py]
        - ref: matrix_index_top
          shift: [-0.3px, 0.5py]
        - ref: matrix_index_top
          shift: [0.4px, 0.5py]
        - ref: matrix_inner_top
          shift: [-0.3px, 0.5py]
        - ref: matrix_inner_top
          shift: [0.5px, 0.53py]
        # start MCU / interconnect space
        # end MCU /interconnect space
        - ref: matrix_inner_bottom
          shift: [0.7px, -0.5py]
        - ref: thumbs_space_cluster
          shift: [0.5px, 0.5py]
        - ref: thumbs_space_cluster
          shift: [0.5px, -0.5py]
        - ref: thumbs_layer_cluster
          shift: [0.3px, -0.5py]
        - ref: thumbs_layer_cluster
          shift: [-0.4px, -0.5py]
        - ref: thumbs_mod_cluster
          shift: [-0.5px, -0.5py]
        - ref: matrix_index_bottom
          shift: [-0.6px, -0.5py]
        - ref: matrix_middle_bottom
          shift: [-0.3px, -0.75py]
        - ref: matrix_ring_bottom
          shift: [-0.3px, -0.55py]
        - ref: matrix_pinky_bottom
          shift: [0.5px, -0.5py]
        - ref: matrix_pinky_bottom
          shift: [-0.5px, -0.5py]
      fillet: 2
  pcb_switch_plate_mounting:
    - what: circle
      radius: mountRadius
      where:
        ref: [matrix_pinky_top]
        shift: [0.68kx, -0.2ky]
    - what: circle
      radius: mountRadius
      where:
        ref: [matrix_index_top]
        shift: [0.63kx, -0.2ky]
    - what: circle
      radius: mountRadius
      where:
        ref: [thumbs_layer_cluster]
        shift: [0.55kx, -0.15ky]
    - what: circle
      radius: mountRadius
      where:
        ref: [matrix_middle_bottom]
        shift: [0, -0.7ky]
    - what: circle
      radius: mountRadius
      where:
        ref: [matrix_ring_bottom]
        shift: [-0.5kx, -0.42py]
  pcb_mcu_cover_mounting:
    - what: circle
      radius: mountRadius
      where:
        ref: [matrix_inner_top]
        shift: [0.68kx, 0.405py]
    - what: circle
      radius: mountRadius
      where:
        ref: [matrix_inner_top]
        shift: [1.95kx, 0.5py]
    - what: circle
      radius: mountRadius
      where:
        ref: [matrix_inner_bottom]
        shift: [2.23kx, -0.4py]
    - what: circle
      radius: mountRadius
      where:
        ref: [matrix_inner_bottom]
        shift: [0.925kx, -0.2py]
  pcb_with_keys:
    - name: pcb_board
    - operation: subtract
      name: keys
    - operation: subtract
      name: pcb_switch_plate_mounting
    - operation: subtract
      name: pcb_mcu_cover_mounting
  switch_plate_with_holes:
    - name: switch_plate
    - operation: subtract
      name: keys
    - operation: subtract
      name: pcb_switch_plate_mounting
    - operation: subtract
      name: pcb_mcu_cover_mounting
pcbs:
  board:
    template: kicad8
    outlines:
      main:
        outline: pcb_board
    footprints:
      choc_hotswap:
        # use regex to split left/right pcb switch pos
        # if you set where to true, you get them on the same kicad
        # plane -> maybe use this to have one PCB for manufacture.
        where: "/^(matrix|thumbs)_/"
        what: ceoloide/switch_choc_v1_v2
        params:
          reversible: true
          hotswap: true
          solder: false
          include_keycap: true
          keycap_width: kx
          keycap_height: ky
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        where: "/^(matrix|thumbs)_/"
        what: ceoloide/diode_tht_sod123
        params:
          reversible: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      mcu:
        what: rp2040zero
        where: matrix_inner_top
        params:
          include_button_cutout: false
          reverse: false
        adjust:
          shift: [0.71px, -0.67py]
          rotate: 5
      interconnect:
        what: usbc
        where: matrix_inner_home
        adjust:
          shift: [1.78px, -0.8py]
          rotate: 95
        params:
          reversible: true
      holeTopPinkyLeft:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_pinky_top]
          shift: [0.68kx, -0.2ky]
      holeTopIndexLeft:
        what: ceoloide/mounting_hole_npth
        where:
            ref: [matrix_index_top]
            shift: [0.63kx, -0.2ky]
      holeLayerLeft:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [thumbs_layer_cluster]
          shift: [0.55kx, -0.15ky]
      holeBottomMiddleMiddle:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_middle_bottom]
          shift: [0, -0.7ky]
      holeBottomRingMiddle:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_ring_bottom]
          shift: [-0.5kx, -0.42py]
      holeMCUCoverTopLeft:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_inner_top]
          shift: [0.68kx, 0.405py]
      holeMCUCoverTopRight:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_inner_top]
          shift: [1.95kx, 0.5py]
      holeMCUCoverBottomRight:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_inner_bottom]
          shift: [2.23kx, -0.4py]
      holeMCUCoverBottomLeft:
        what: ceoloide/mounting_hole_npth
        where:
          ref: [matrix_inner_bottom]
          shift: [0.925kx, -0.2py]
cases:
  bottom_case:
    - name: pcb_board
      extrude: 1
  switch_plate_case:
    - name: switch_plate_with_holes
      extrude: 1
