[keyboard]
name = "default"
product_name = "atomic_36"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Edward Evans"
chip = "rp2040"

[layout]
rows = 4
cols = 10
map = """
(0, 0, L)  (0, 1, L)  (0, 2, L)  (0, 3, L)  (0, 4, L)    (0, 5, R)  (0, 6, R)  (0, 7, R)  (0, 8, R)  (0, 9, R)
(1, 0, L)  (1, 1, L)  (1, 2, L)  (1, 3, L)  (1, 4, L)    (1, 5, R)  (1, 6, R)  (1, 7, R)  (1, 8, R)  (1, 9, R)
(2, 0, L)  (2, 1, L)  (2, 2, L)  (2, 3, L)  (2, 4, L)    (2, 5, R)  (2, 6, R)  (2, 7, R)  (2, 8, R)  (2, 9, R)
                      (3, 2, L)  (3, 3, L)  (3, 4, L)    (3, 5, R)  (3, 6, R)  (3, 7, R)
"""

[keymap]
layers = 3

[[keymap.layer]] # layer 0
keys = """
Q           W     E     R     T         Y      U     I        O     P
MT(A, LGui) S     D     F     G         H      J     K        L     Semicolon
Z           X     C     V     B         N      M     Comma    Dot   MT(Slash, RAlt)
                  LCtrl MO(1) Space     Enter  MO(2) RShift
"""

[[keymap.layer]] # layer 1
keys = """
Kc1     Kc2        Kc3        Kc4        Kc5         Kc6        Kc7        Kc8       Kc9        Kc0
Tab     Home       PageDown   PageUp     End         Left       Down       Up        Right      Backspace
Escape  _          _          _          _           _          _          _         _          Delete
                   LCtrl      MO(1)      Space       Enter      MO(2)      RShift
"""

[[keymap.layer]] # layer 2
keys = """
WM(Kc1, LShift)  WM(Kc2, LShift)    WM(Kc3, LShift)  WM(Kc4, LShift)  WM(Kc5, LShift)       WM(Kc6, LShift)   WM(Kc7, LShift)  WM(Kc8, LShift)         WM(Kc9, LShift)           WM(Kc0, LShift)
_                WM(Grave, LShift)  Grave            Quote            _                     KpMinus           KpEqual          LeftBracket             RightBracket              Backslash
_                _                  _                _                _                     WM(Minus, LShift) KpPlus           WM(LeftBracket, LShift) WM(RightBracket, LShift)  WM(Backslash, LShift)
                                    LCtrl            MO(1)            Space                 Enter             MO(2)            RShift
"""

# default profile for HRM with all tap-hold features
[behavior.morse]
enable_flow_tap = true
prior_idle_time = "120ms"
hold_on_other_press = true
hold_timeout = "250ms"
gap_timeout = "250ms"

[storage]
enabled = true

[split]
connection = "serial"

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0
serial = [{ instance = "PIO0", tx_pin = "PIN_8", rx_pin = "PIN_8" }]

[split.central.matrix]
matrix_type = "normal"
row_pins = ["PIN_29", "PIN_28", "PIN_27", "PIN_26"]
col_pins = ["PIN_15", "PIN_14", "PIN_13" ,"PIN_12", "PIN_11"]
bootmagic = [0, 0] # This is "Q"

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 5
serial = [{ instance = "PIO0", tx_pin = "PIN_9", rx_pin = "PIN_9" }]

[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["PIN_29", "PIN_28", "PIN_27", "PIN_26"]
col_pins = ["PIN_11" ,"PIN_12", "PIN_13", "PIN_14", "PIN_15"]
bootmagic = [0, 4] # This is "P"

[rmk]
split_peripherals_num = 1
